FROM python:3.11-slim

WORKDIR /mlflow

RUN pip install --no-cache-dir mlflow psycopg2-binary boto3

RUN mkdir -p /mlflow/artifacts

EXPOSE 5000

CMD ["mlflow", "server", "--host", "0.0.0.0", "--port", "5000"]
