replicaCount: 3

image:
  repository: username/fastapi-app
  tag: "v1.2.0"
  pullPolicy: Always

resources:
  enabled: true
  requests:
    memory: "256Mi"
    cpu: "200m"
  limits:
    memory: "1Gi"
    cpu: "2000m"

ingress:
  enabled: true
  host: prod.example.com
